[workspace]
members = [
    "common",
    "macro",
    "codec",
]
resolver = "2"

[profile.release-lto]
inherits = "release"
strip = "symbols"
lto = "fat"
panic = "abort"
codegen-units = 1

[package.metadata.cargo-all-features]
denylist = ["binary", "gui"]
