[package]
name = "zalgo-codec-macro"
version = "0.1.1"
edition = "2021"
authors = ["Alex Keizer (alex@keizer.dev)", "Johanna Sörngård (jsorngard@gmail.com)"]
description = "This crate provides the `zalgo_embed!` macro for compiling zalgo-encoded source code"
repository = "https://github.com/JSorngard/zalgo_codec/tree/main/macro"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true


[dependencies]
zalgo-codec-common = "0.2.4"
syn = "1.0"
