[package]
name = "zalgo-codec-macro"
version = "0.1.0"
edition = "2021"
authors = ["Alex Keizer (alex@keizer.dev)", "Johanna Sörngård (jsorngard@gmail.com)"]
description = "This crate provides the `zalgo_embed!` macro for compiling zalgo-encoded source code"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true


[dependencies]
zalgo-codec-common = {path = "../common"}
syn = "1.0"
