[package]
name = "zalgo-codec"
authors = ["Johanna Sörngård (jsorngard@gmail.com)", "Scott Conner", "Alex Keizer (alex@keizer.dev)"]
version = "0.5.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/JSorngard/zalgo_codec/tree/main/codec"
description = "A crate for converting an ASCII text string to a single unicode grapheme cluster and back. Provides a macro for executing Rust source code that has been encoded in this way. Additionally provides a function that encodes Python code and wraps it in a decoder so that it retains its functionality."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zalgo-codec-common = {path = "../common"}
zalgo-codec-macro = {path = "../macro"}

[dev-dependencies]
rand = "0.8"
unicode-segmentation = "1.10.1"

[features]
default = ["files"]
files = ["zalgo-codec-common/files"]
